### PR TITLE
Update package.json after clone repository

### PR DESCRIPTION
**Pull request by joao-alberto**

### CODE REVIEW

**Comment by willianjusten** [comment]
Hi @psicotropicos, we are building this project yet. So, there are a lot of things to change. I'll let @Nipher to analyse this PR, but I think we need more time to build our first structure, so we can accept PR later.

**Comment by joao-alberto** [comment]
@willianjusten Thanks for fast answering, I understand I was a little hasty, sorry about that. :smile:

**Comment by willianjusten** [comment]
Relax man, we love opensource because of that, the desire to help everyone =D
We are planning to do some things this week and I'll be very happy with your feedback and help.

**Comment by jmpas** [comment]
haha, it's so awesome to see people contributing!

So, I won't start a discussion here, I've created another issue to discuss how we are going to replace the values with input data from the user.

Issue: #2

Feel free to suggest any other idea or improvement :)

**Comment by jmpas** [comment]
Done #2

**Pull request closed without merging**
